capabilities:
  # Plaid
  link_session:      "Plaid::LinkSession"
  exchange_token:    "Plaid::ExchangeToken"
  verify_income:     "Plaid::VerifyIncome"
  initiate_transfer: "Plaid::InitiateTransfer"
  transfer_status:   "Plaid::TransferStatus"

  # SendGrid
  send_email: "Sendgrid::SendEmail"

  # Submissions
  submit_form: "Submissions::SubmitForm"
