service: budget-clear-proxy
image: ghcr.io/emerson-argueta/budget-clear-proxy

servers:
  web:
    - 192.168.4.158

ssh:
  user: devadmin
  keys:
    - ~/.ssh/id_ed25519_mac

registry:
  server: ghcr.io
  username: emerson-argueta
  password:
    - KAMAL_REGISTRY_PASSWORD

builder:
  arch: amd64

proxy:
  ssl: false
  app_port: 3000

env:
  secret:
    - SECRET_KEY_BASE
    - ENCRYPTION_KEY
    - PLAID_CLIENT_ID
    - PLAID_SECRET
    - STRIPE_SECRET_KEY
    - STRIPE_WEBHOOK_SECRET
    - STRIPE_PUBLISHABLE_KEY
  clear:
    RAILS_ENV: production
    RAILS_LOG_TO_STDOUT: true
    RAILS_SERVE_STATIC_FILES: true
    DEFAULT_MARKUP_PERCENT: "0"
    REQUIRE_PAYMENT: "false"

volumes:
  - "budget_clear_proxy_storage:/rails/storage"

aliases:
  console: app exec --interactive --reuse "bin/rails console"
  shell: app exec --interactive --reuse "bash"
  logs: app logs -f
